baseURL: "https://www.esempio-dominio.com/"
title: "Iuliana David - Mental Coach"
defaultContentLanguage: "it"
defaultContentLanguageInSubdir: false
enableRobotsTXT: true

pagination:
  pagerSize: 10

# Multilingua
languages:
  it:
    languageName: "Italiano"
    weight: 1
    title: "Iuliana David - Mental Coach"
    params:
      heroTitle: "Iuliana David"
      heroSubtitle: "Mental Coach e tecnico facilitatore nel cambiamento"
    menu:
      main:
        - name: "Life Coach - Badanti"
          url: "/life-coach-badanti/"
          weight: 10
        - name: "Comunicazione - Aziende"
          url: "/comunicazione-aziende/"
          weight: 20
        - name: "Sport - Attestati"
          url: "/sport-attestati/"
          weight: 30
        - name: "Contatti"
          url: "/contatti/"
          weight: 40

  ro:
    languageName: "Română"
    weight: 2
    title: "Iuliana David - Mental Coach"
    params:
      heroTitle: "Iuliana David"
      heroSubtitle: "Mental Coach și facilitator al schimbării"
    menu:
      main:
        - name: "Life Coach - Îngrijitoare"
          url: "/life-coach-badanti/"
          weight: 10
        - name: "Comunicare - Companii"
          url: "/comunicazione-aziende/"
          weight: 20
        - name: "Sport - Certificate"
          url: "/sport-attestati/"
          weight: 30
        - name: "Contact"
          url: "/contatti/"
          weight: 40

# Dove metteremo gli asset (CSS, ecc.)
assetDir: "assets"