baseURL: "/"
title: "Iuliana David - Mental Coach"
defaultContentLanguage: "it"
defaultContentLanguageInSubdir: false
enableRobotsTXT: true

pagination:
  pagerSize: 10

# -------------------------
# MULTILINGUA + MENU
# -------------------------
languages:
  it:
    languageName: "Italiano"
    languageCode: "it"
    weight: 1
    title: "Iuliana David - Mental Coach"
    menu:
      main:
        - name: "Life Coach – per persone intraprendenti"
          url: "/life-coach-badanti/"
          weight: 10
        - name: "Team Building – Aziendale"
          url: "/comunicazione-aziende/"
          weight: 20
        - name: "Mental Coach Sportivo – Oltre i tuoi limiti"
          url: "/sport-attestati/"
          weight: 30
        - name: "Info & Contatti – Formazione"
          url: "/contatti/"
          weight: 40

  ro:
    languageName: "Română"
    languageCode: "ro"
    weight: 2
    title: "Iuliana David - Mental Coach"
    menu:
      main:
        - name: "Life Coach – pentru persoane întreprinzătoare"
          url: "/life-coach-badanti/"
          weight: 10
        - name: "Team Building – Companii"
          url: "/comunicazione-aziende/"
          weight: 20
        - name: "Mental Coach Sportiv – Dincolo de limite"
          url: "/sport-attestati/"
          weight: 30
        - name: "Informații & Contact – Formare"
          url: "/contatti/"
          weight: 40

# Dove metteremo gli asset (CSS, ecc.)
assetDir: "assets"

markup:
  goldmark:
    renderer:
      unsafe: true